apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/prom-data