{{- if .Values.ingress.enabled }}
{{- $servicePort := .Values.service.externalPort -}}
{{- $serviceName := include "chartmuseum.fullname" . -}}
{{- $ingressExtraPaths := .Values.ingress.extraPaths -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chartmuseum.fullname" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  labels:
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
{{ include "chartmuseum.labels.standard" . | indent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .name }}
      http:
        paths:
          {{- range $ingressExtraPaths }}
          - path: {{ default "/" .path | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                {{- if $.Values.service.servicename }}
                name: {{ $.Values.service.servicename }}
                {{- else }}
                name: {{ default $serviceName .service }}
                {{- end }}
                port:
                  number: {{ default $servicePort .servicePort }}
          {{- end }}
          - path: {{ default "/" .path | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                {{- if $.Values.service.servicename }}
                name: {{ $.Values.service.servicename }}
                {{- else }}
                name: {{ default $serviceName .service }}
                {{- end }}
                port:
                  number: {{ default $servicePort .servicePort }}
    {{- end }}
  tls:
    {{- range .Values.ingress.hosts }}
    {{- if .tls }}
    - hosts:
        - {{ .name }}
      secretName: {{ .tlsSecret }}
    {{- end }}
    {{- end }}
{{- end -}}