apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: webali/nginx-monitoring:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
