##
# Repo: fluent/fluent-bit
##
logLevel: debug

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On
  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Exclude_Path /var/log/containers/*nginx*.log
        multiline.parser docker, cri
        Tag k8s.common.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    [INPUT]
        Name tail
        Path /var/log/containers/*nginx*.log
        Tag k8s.nginx.*
        Parser docker_no_time
        Mem_Buf_Limit 5MB
        Skip_Long_Lines Off
    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name kubernetes
        Match k8s.*
        Kube_URL https://kubernetes.default.svc.cluster.local:443
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name nest
        Match k8s.*
        Operation lift
        Nested_under kubernetes
        Add_prefix kubernetes_

    [FILTER]
        Name nest
        Match k8s.*
        Operation lift
        Nested_under kubernetes_labels
        Add_prefix kubernetes_labels_
  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name es
        Match k8s.common.*
        Host elasticsearch.observability.svc.cluster.local
        Logstash_Format On
        Logstash_Prefix kube
        Retry_Limit False
        Suppress_Type_Name On
    [OUTPUT]
        Name es
        Match k8s.nginx.*
        Host elasticsearch.observability.svc.cluster.local
        Logstash_Format On
        Logstash_Prefix nginx
        Retry_Limit False
        Suppress_Type_Name On
    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch.observability.svc.cluster.local
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Suppress_Type_Name On
  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L