prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchExpressions:
        - key: app
          operator: In
          values:
            - prometheus-elasticsearch-exporter
            - kube-prometheus-stack-alertmanager
            - kube-prometheus-stack-apiserver
            - kube-prometheus-stack-coredns
            - kube-prometheus-stack-kube-controller-manager
            - kube-prometheus-stack-kube-etcd
            - kube-prometheus-stack-kube-proxy
            - kube-prometheus-stack-kubelet
            - kube-prometheus-stack-operator
            - kube-prometheus-stack-prometheus
            - prometheus-node-exporter
            - grafana
            - prometheus
            - prometheus-operator
