apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
  namespace: default
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
    matchExpressions:
      - key: env
        operator: NotIn
        values: [prod]
      - key: tier
        operator: In
        values: [front]
  minReadySeconds: 0
  template:
    metadata:
      labels:
        app: web
        tier: front
        env: dev
    spec:
      containers:
        - name: web
          image: webali/go-http-server:v0.2.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /logs
              name: logs
      volumes:
        - name: logs
          emptyDir: {}
