apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: server
        image: webali/hipster-frontend:v0
        env:
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: /catalog
          - name: CURRENCY_SERVICE_ADDR
            value: "http://localhost:8000"
          - name: CART_SERVICE_ADDR
            value: "http://localhost:8889"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "http://localhost:8890"
          - name: CHECKOUT_SERVICE_ADDR
            value: "http://localhost:8890"
          - name: SHIPPING_SERVICE_ADDR
            value: "http://localhost:8891"
          - name: AD_SERVICE_ADDR
            value: "http://localhost:8892"