apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework  # имя CRD должно иметь формат plural.group
spec:
  group: otus.homework      # Группа, отражается в поле apiVersion CR
  names:                    # различные форматы имени объекта CR
    kind: MySQL             # kind CR
    plural: mysqls
    singular: mysql
    shortNames:
      - ms
  scope: Namespaced         # Данный CRD будер работать в рамках namespace
  versions:                 # Список версий
    - name: v1
      served: true          # Будет ли обслуживаться API-сервером данная версия
      storage: true         # Версия описания, которая будет сохраняться в etcd
      schema:
        openAPIV3Schema:
          type: object
          required:
            - apiVersion
            - kind
            - metadata
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
            spec:
              type: object
              required:
                - image
                - database
                - root_password
                - user_name
                - user_password
                - storage_size
              properties:
                image:
                  type: string
                database:
                  type: string
                root_password:
                  type: string
                user_name:
                  type: string
                user_password:
                  type: string
                storage_size:
                  type: string
            status:
              type: object
              # https://kopf.readthedocs.io/en/stable/configuration/?highlight=%22x-kubernetes-preserve-unknown-fields%22#handling-progress
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}