apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: webali/hipster-frontend:latest
    name: frontend
    resources: {}
    env:
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: /catalog
      - name: CURRENCY_SERVICE_ADDR
        value: "http://localhost:8888"
      - name: CART_SERVICE_ADDR
        value: "http://localhost:8889"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "http://localhost:8890"
      - name: CHECKOUT_SERVICE_ADDR
        value: "http://localhost:8890"
      - name: SHIPPING_SERVICE_ADDR
        value: "http://localhost:8891"
      - name: AD_SERVICE_ADDR
        value: "http://localhost:8892"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
